### ISSUE TITLE
チュートリアルの確認（将来予測）

### ISSUE THREAD

**Issue by osamusakai** [ichimomo/future-rvpa#10]
チュートリアルの「5.将来予測」のところで、future.vpaの引数rec.arg=list()のlist内にrho=HS.par0$pars$rhoを与える必要があると思います。
結果の図（future.vpa-1.png）も、以下のように変わるのではないでしょうか。

![future vpa-1re](https://user-images.githubusercontent.com/5091111/47422821-87fc0a00-d7be-11e8-8015-adef5cd4e438.png)

**Comment by ichimomo** [comment]
コメントありがとうございます．
HS.par0ではARを計算していないので，rhoは与える必要がなく，与えない(NULLだ)と自動的に0を代入するようにしていますが（future2.1.rの608行目あたり），それがうまく動いていないということでしょうか？いちおうrhoの指定あり・なしで結果を比較しましたが，そんなに変わらないような？？

ただ，たしかに，自己相関を考慮した場合にも同じコードで計算できるように，明示的にしていておいたほうが良いですね．

修正してみました
https://github.com/ichimomo/future-rvpa/commit/e8334f629511b6fe8f7e46407d289734e73c34e3
