### ISSUE TITLE
est.MSY関数内のGT計算

### ISSUE THREAD

**Issue by osamusakai** [ichimomo/future-rvpa#11]
future2.1.rについて、est.MSY関数のGT計算部分（3860-3861行目）は以下の修正が必要と思います；

現状：
`        GT <- Generation.Time(vpares,maa.year=fres.HS$input$maa.year,
                              M.year=fres.HS$input$M.year)`

修正案：
`        GT <- Generation.Time(vpares,maa.year=farg$maa.year,
                              M.year=farg$M.year) `

**Comment by ichimomo** [comment]
対応しました！
