### ISSUE TITLE
管理基準値・ABC計算チュートリアル

### ISSUE THREAD

**Issue by kurota** [ichimomo/future-rvpa#12]
https://ichimomo.github.io/future-rvpa/future-doc-abc.html

わかりやすいチュートリアルの作成ありがとうございます。コードと関係ありませんが、2つ修正点に気づいたので報告します。

・「(5-3) 年齢別体重が資源尾数に影響される場合の将来予測（2018/06/12新オプションとして追加）」

「30系群であてはめた例はこちら (データは1年分古いです)」のリンクが切れています。

・「8. ABC計算までのまとめ（時間がない人はここからスタート）」

オブジェクトrefsが（まとめ内で）定義されていないので、エラーになります。

**Comment by ichimomo** [comment]
こちらで対応しました。
https://github.com/ichimomo/future-rvpa/commit/ee1a97e3c4c21d3d7b0955cdc1f89692df377a7d
コメントありがとうございます
