### ISSUE TITLE
futureの出力結果について（スケソ日本海対応）

### ISSUE THREAD

**Issue by YuuhoYamashita** [ichimomo/future-rvpa#14]
将来予測の推定結果を確認していたところ、加入尾数が2020年からしか変化していませんでした(2歳加入という設定が影響しているのではないかと思うのですが)。

start.yearとrec.newの指定を2016年からとすることで回避できましたが、現状のfutureコードでは2016年のFも最終年（2017年）の値となってしまいます。
future2.1の742～748行目にある　tmp0[jj]　の部分を　tmp0[j]　に修正しても大丈夫でしょうか？

              faa[,tmp[j],] <- res0$faa[,tmp0[j]] #tmp0[jj]
              waa[,tmp[j],] <- res0$input$dat$waa[,tmp0[j]] #tmp0[jj]
              if(!is.null(res0$input$dat$waa.catch)){
                waa.catch[,tmp[j],] <- res0$input$dat$waa.catch[,tmp0[j]] #tmp0[jj]
              }
              else{
                waa.catch[,tmp[j],] <- res0$input$dat$waa[,tmp0[j]] #tmp0[jj]
              }

ABCにばらつきが出ないのは加入量を指定していたせいかと思ってまして、気付くのが遅くなってすみません。

あと、現状det.runはTRUEでもFALSEでも1試行目の値は確率論的な試行結果になってるのでしょうか？

（コメント修正履歴は気にしないでください・・・）

**Comment by ichimomo** [comment]
issueへのコメントありがとうございます！

日本海スケトウの設定をもともとどのようにしたいのかがあまり把握できていないため、もう少し詳しいことを聞いても良いでしょうか？

rec.newオプションを使って、何年の加入を外から与えたいのでしょうか？（rec.newに加入尾数だけを入れると、将来開始直後の加入尾数が置き換わります。list(year=XXX, rec=XXX)とすると、対応する年の加入尾数が置き換わります）←rec.new=list(year=XXX,rec=XXX)と指定すればうまくいったということでＯＫでしょうか？

一方で、start.yearはなぜ2016年からにする必要があるのでしょうか？

たぶん日本海スケトウの複雑な状況をあんまり理解できておりませんので、
資源評価が何年までで、加入を置き換えたい年が何年で、（その他、pre.catchで指定したい年やcurrent FまたはＨＣＲで漁獲したい年なのか）など、まとめて情報を頂き、そのうえでどの部分が想定と違ってしまっているのか教えて頂けるとありがたいです。

よろしくお願いします。

（また、https://github.com/ichimomo/future-rvpa/tree/master/sample/nsk2012　に、2012年の資源評価結果をもとにしたRVPA開発当初に作ったスケトウのデータとコードを置いてみました（将来予測部分はＨＳによるあてはめに書き直しています）。こちらのコードでも同様の問題が再現できるか、もしわかりましたら見て頂いてもよいかと思います。）

**Comment by YuuhoYamashita** [comment]
nsk2012.R　確認しました。

やはり同様に、
rec.new <- list(year=2012,rec=385496)
としか指定していないのに、2014年からしか資源尾数に誤差がはいっていないようです。

 fres.nsk$naa[1,1:5,1:5]
　　　1　　　　　2　　　　　3　　　　　4　　　　　5
2012　385496.0　385496.00　385496.00　385496.00　385496.00
2013　106657.6　106657.64　106657.64　106657.64　106657.64
2014　108224.6　 72283.00　 90056.44　　 66644.00　95378.07
2015　117129.1　 89064.87　 36340.60　　163358.06　63701.23
2016　142856.0　 72285.82 　285007.92　　96214.56　142699.71

**Comment by ichimomo** [comment]
ご確認ありがとうございます。

私も2012ねんデータで確認して同じ現象を見つけました。加入年齢が1歳以上で、親魚量を過去のＶＰＡ結果から参照する場合、確率的なサンプリングがなされておりませんでした。

修正しましたのでたしかめてみてください
https://github.com/ichimomo/future-rvpa/commit/50c2a176342742e4756d5cbc30a5791baeaa5276

それとは別に

future2.1の742～748行目にある　tmp0[jj]　の部分を　tmp0[j]　に修正しても大丈夫でしょうか？
```
          faa[,tmp[j],] <- res0$faa[,tmp0[j]] #tmp0[jj]
          waa[,tmp[j],] <- res0$input$dat$waa[,tmp0[j]] #tmp0[jj]
          if(!is.null(res0$input$dat$waa.catch)){
            waa.catch[,tmp[j],] <- res0$input$dat$waa.catch[,tmp0[j]] #tmp0[jj]
          }
          else{
            waa.catch[,tmp[j],] <- res0$input$dat$waa[,tmp0[j]] #tmp0[jj]
          }
```
については別のバグかもしれないので、こちらは別途確認してみます。

**Comment by ichimomo** [comment]
start.yearをVPA推定年以前に指定するときに見られた状況は明らかにバグだと思われましたので、こちらも　https://github.com/ichimomo/future-rvpa/commit/88c519a834ba1bc8c4b7916b63aa1cd7ea52cd57　にて修正しました！
