### ISSUE TITLE
ABCの暫定計算をするさいの注意事項

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/future-rvpa#19]
- ARありの場合，est.MSY関数の引数として必ずresid.year=1を設定してください（そうでないとARの設定は反映されません）
   - https://github.com/ichimomo/future-rvpa/commit/18f97c864060d5a0c9f9f84c91dd03a49f94c940にて注意事項をチュートリアルにも追記しました

- 再生産関係のフィットでは，L1オプションも試してみてください．
   - fit.SRのオプションでmethod="L1"とします

**Comment by osamusakai** [comment]
未だに混乱しているのですが（申し訳ないです）、ARなしの場合でも、HCRにはAR有りのもの（BmsyARとかBbanARとか）を使用するという理解で良いでしょうか？

**Comment by ichimomo** [comment]
または「ARありの管理基準値」は、「なしの場合と比較して1割以上異なっていたら」とかにしましょうか？細かい数字がちょっとづつ変わっているのもややこしいですし、、、
