### ISSUE TITLE
plot.HCR関数のコード

### ISSUE THREAD

**Issue by osamusakai** [ichimomo/future-rvpa#23]
future2.1.rのplot.HCR関数ですが、
5976行目の以下の部分は
**`paste("F2018=",round(Frec*beta*Fmsy,2),"","Fcurrent (",`**
F2018ではなくてF2019ではないでしょうか？
多分、ABC.yearのFに対応している必要があると思うのですが…

**Comment by ichimomo** [comment]
こちらのコメントに対応して関数を修正しようとしていて気づきましたが、今のHCRで使うBって（(B-Bban)/(Blim-Bban)の）将来予測のABC算定年のＢなんですよね。でもこのコードだと現状のB(VPA最終年のSSB)を入れているので実際に使われているHCRのFとはちょっと違う感じになっています。
将来予測のSSBはABC算定年の直近といえどもある程度分布があるんで、HCRをどう可視化するかちょっと工夫しないといけないと思います。少々考えさせてください。

またなにかアイディアありましたらそちらで作ってpull requestして頂いても大丈夫です。

**Comment by osamusakai** [comment]
確かにおっしゃる通りで、予測されるSSBがBlimやBbanを含む幅を持って推算される場合は、"実際の運用上"でもややこしいことになりそうです。BbanやBlimと比較考慮する基準が、そもそもVPA最終年のSSB値か、ABC算出年のSSB値かというのは、議論のあるところですから整理が必要だと思います。
