### ISSUE TITLE
Kobe chartのy軸はどうすべきか？

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/future-rvpa#24]
Kobe chartのy軸は一般にF/Fmsyで示されますが，年齢別モデルで資源評価されていて選択率が年々変わるような場合にはどうやってF/Fmsyを示すかというのはけっこう難しい問題です．思いつく解決策としては以下のようなものがあると思うんですが，どうすべきか．．．

1. 漁獲率を使う
漁獲率（漁獲量/資源量）＝Ｕ_yを毎年計算する．また，別途，特定の選択率（だいたいはFcurrent）におけるMSYを達成するときの漁獲率をUmsyとし，U_y/U_msyをKobe chartのy軸とする．
- 使用例：Ram Legacy databaseを使った解析(たとえばWorm et al 2009）ではKobe chartのy軸にはUが使われている．それに則って，Ichinokawa et al. (2017)でもUを使って漁獲圧の時系列を示している
- 利点：わかりやすい．数字が小さめに出る．
- 欠点：正確ではない．選択率によってはU<Umsyになっているのに実際にはF>Fmsyになっている，または逆の状態になっているような状況も発生する恐れ．Umsy（MSYを達成するときの漁獲率）を一つの重要な尺度として利用することになる（利点？）

2. %SPR換算する
毎年のF at ageを%SPR換算し，MSYを達成するときの%SPRに相当する%SPR(%SPR_MSY)に対するFの乗数としてあらわす．
- 欠点：説明するのが面倒くさいくらい，ちょっと計算方法が複雑．%SPR_MSYは特定の選択率におけるMSYの値なので，別の選択率においてはその%SPRがMSYになるとは限らない．
- 利点：毎年のF at ageが資源に与える影響を正確に評価できる
- 使用例：たしかクロマグロの資源評価の中でこのようなやり方がF の影響の強さを正確に評価するのによいとNOAAの研究者(Kevin Piner)が言っていた

3. 毎年のF at ageごとにMSYを推定する
ネット検索していたらIATTCではこのようにやっているらしい．
https://www.iattc.org/Meetings/Meetings2011/May/_English/SAC-02-11-Evaluation-of-Kobe-plot-and-matrix.pdf
毎年のF at age（実際には3年の移動平均）における選択率をもとにして，ＭＳＹを達成するときのＦへの乗数を計算する．
- 利点：方法がちょっと面倒くさいわりに説明も難しいが，最もストレートにF/Fmsyを解釈するとこうなるのか？
- 欠点：方法がちょっと面倒くさいわりに説明も難しい．Stochastic simulationを使ってMSYを推定する場合，各選択率毎にMSYを推定しなければいけないので計算時間がかかる．選択率が異なる毎年毎年で，想定されるB_msyも異なってくる．
- 使用例：IATTCとかで利用されている？

他になにか良いアイディアなどありましたらお寄せください．とりあえず，1,2,3でどのくらい見え方が違ってくるのかやってみようかとは思っています．Uで見る場合のほうがF>Fmsyの場合にFmsyを「越している度」が一番小さくなります．

**Comment by osamusakai** [comment]
「2. %SPR」のところでクロマグロの例（太平洋くろまぐろだと思いますが）を示されていますが、太平洋クロマグロでのSPRはSpawning Potential Ratioであって、Spawning biomass par Recruitmentではないです。詳しくは御グループの秋田さんに聞いて頂ければと思います。
一応、今年の春ごろに国際水研の福田さん、秋田さんと一緒に作った資料を添付しておきます。 
[SPR定義.pdf](https://github.com/ichimomo/future-rvpa/files/2867269/SPR.pdf)

**Comment by ichimomo** [comment]
フォローありがとうございます．私のクロマグロ時代の記憶も古いもので．．．

資料を読むと
![image](https://user-images.githubusercontent.com/44047915/52827172-06cad900-3107-11e9-8be8-0828ccf48814.png)
とあり，クロマグロの場合は一腹産卵数などを考慮しているのでSPR\*と%SPRを区別して使っている，という理解で良いでしょうか？
逆に，そのような考慮がない場合（多分沿岸資源の多くの系群で）はSPR\*=%SPRでOKですか？

別にクロマグロで使うわけではないので，あまり話を複雑にしたくないので．．．

**Comment by osamusakai** [comment]
理由は失念しましたが、クロマグロの場合は一腹産卵数を体重とリニアな関係と仮定してSS3を設定していたと思います。
そもそも、近年のISCでの議論では基本的にSpawning Potential Ratio（SPR*）しか使っていないので、%SPRはほとんど意識されていません。
1-SPR*が漁獲圧の指標（Fの代替…というのですかね）として使用されているという状況です。

SPR*=%SPRではなく、
Spawning Potential(F=0)がSpawning biomass par Recruitment(F=0)と対応します。
そういえば、本件については中山さんも詳しいです。ぜひ、ご相談いただければと思います。

**Comment by ichimomo** [comment]
まあ，クロマグロでは%SPRをベースにした似たような指標を使っている，ということですよね．
本題はKobe chartのy軸として何を使うか，ということなんですが，この点については何かありますでしょうか？

**Comment by ichimomo** [comment]
正確にクロマグロではどうやっているかは中山さん・秋田さんに聞いておきます．
クロマグロで計算しているやり方と同じ，と言うと水産庁のほうも納得するかもしれないですね

**Comment by osamusakai** [comment]
クロマグロで、というよりは統合モデルSS3のデフォルトのアウトプットがSPR*なので、という状況かなと思います。米国でも、SS3を使っていない資源評価種については、時々%SPRの話が評価報告書に出てきますので…。将来的に日本でもSS3を使うようになるのであれば、SPR*も候補の一つになり得るのでしょう。

色々話がそれてしまいましたが、個人的にはKobe-plotは行政官・漁業者へのメッセージとして視覚的に訴える要素が強いので、現段階では簡単に説明できるものを優先することが望ましいと思います。厳密性を考えなければならないニーズがどこまであるかにより、何をy軸に使うかが決まってくるのではないでしょうか。MSC認証とかと関係するのでしたっけ？

**Comment by ichimomo** [comment]
先日の，水研機構の成果報告会でも，みなと新聞の太田さんとかが，「水研の研究者の説明は難しすぎる，厳密に示そうとするあまり，わかりやすさを犠牲にしている」とおっしゃってました．

となると一番簡単なU（漁獲率）ですかね？
ただ，水研の研究者自身はU表示によるKobe chartは厳密ではない旨を認識して使う必要はありますね．

MSC認証が必要で厳密に計算したいということであればその都度計算すれば良いかとは思います．
