### ISSUE TITLE
Kobe chartの移動平均オプション

### ISSUE THREAD

**Issue by osamusakai** [ichimomo/future-rvpa#28]
単純に興味からの質問なのですが、Kobeチャートにある移動平均オプションについて教えてください。
Kobeチャートを書く際に、移動平均を使うのが一般的になったのでしょうか？
今まで、Kobeチャートを書くときに移動平均の値を用いたことが無かったもので、考えたことがありませんでした。何か背景がありましたら教えて頂けないでしょうか？

**Comment by ichimomo** [comment]
このissueからもリンクをはっていますが，
https://github.com/ichimomo/future-rvpa/issues/24#issue-410356418

EPOのマグロのKobe chartを書く場合　↓　に，
https://www.iattc.org/Meetings/Meetings2011/May/_English/SAC-02-11-Evaluation-of-Kobe-plot-and-matrix.pdf
毎年毎年のＦを3年づつ移動平均したＦをF/Fmsyに換算するという方法でやっているようです．
私も，ちょうどマイワシなどのKobe chartを書いているとかなり値がばたついて見にくいという状況があり，なるほど，移動平均でもいいのかな，と移動平均オプションをつけてみた次第です．上記のEPOのKobe chartでも，B/Bmsyについては特に移動平均は使っていないみたいなので，B/Bmsyのほうは余計かもしれませんが，Ｂでも移動平均を使ったら全体の傾向が見やすくなるのであれば使っても良いかなと思います．どうせそんな定量的な図ではなく，状態の可視化のための図なので．．．

という次第です．お好みで（但し何年平均かは明記して）やってみてください．
なんか文句を言われたら教えてください．

お返事遅くなりました
