### ISSUE TITLE
yield curve

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/future-rvpa#29]
・将来予測結果をつける
・MSYのデータを切り出したものをインプットとして使えるようにする

**Comment by YuuhoYamashita** [comment]
科学者会議向け資料で、漁獲量曲線について各管理基準での年齢構成に関する説明が求められているようなのですが、yield curve の値を大雑把にでも数値で出力できるようになったりはしませんでしょうか？

**Comment by ichimomo** [comment]
このあたりでいろいろ対応しました．

https://github.com/ichimomo/future-rvpa/blob/087039149ddae003ea5ec79f82eb6cf0a08b3621/sample/make_report1/2make_report.R#L24-L44

- est.MSYの返り値の中のtraceのみを与えても動くようにもなっています
- get.trace関数＋いくつかの追加コードでyield curveの値も取り出せます
- 将来予測結果やVPA結果をリストで与えると，その値も上書きされます
- xlim.scale, ylim.scaleでｘ軸，ｙ軸の調整ができます

**Comment by YuuhoYamashita** [comment]
ご対応ありがとうございました。
 yield.table　非常に便利です。どうもありがとうございました。
