### ISSUE TITLE
漁獲量の変動に関するパフォーマンス指標

### ISSUE THREAD

**Issue by osamusakai** [ichimomo/future-rvpa#32]
新ABC算定規則では、管理目標として以下の三点を強調していたと思います；
1)　不確実性を最大限に考慮して、資源の再生産能力が著しく悪化しないような資源水準を保ち、
2)　長期的に得られる平均漁獲量を最大化すること、
3)　漁獲量の変動をできるだけ最小化すること

今のところ、HCRのβを変えたときに、どのような資源状態・漁獲が期待できるかはKobeIIマトリックスで説明することになると思います。上記１）についてはBtargetの達成確率、２）については各年に平均的に期待できる漁獲量を参照できますが、３）についても何か簡単に説明できるパフォーマンス指標があったほうが良いように思います。
一般的には、AAVを示すことが選択肢だと思います（AAVを知らない人に説明するのは結構むずかしいかもですが…）。アウトプット出来るようにして頂けないでしょうか？

**Comment by ichimomo** [comment]
漁獲量の変動のパフォーマンス指標も，長期的なもの（平衡状態）と短期的なもの（ＨＣＲ依存）に分かれるかなと思います．
- 長期的なもの：平衡状態における漁獲量のCV (F=constant, 世代時間×20年後の各シミュレーションにおける漁獲量のCV)は管理基準値表に追加で出すようにしました => make_RP_tableを書き換えています
https://github.com/ichimomo/future-rvpa/blob/8ff2030afcb0ebbf9c1522294398e22f64af53a4/utilities.r#L161

- 短期的なHCR依存のもの：こちらは何年分のを見たいのか，どんなところに注目するのかで違いますので，目的に応じて書き換えてください．例えばの例をこちらに追記しました

https://github.com/ichimomo/future-rvpa/blob/8ff2030afcb0ebbf9c1522294398e22f64af53a4/sample/make_report1/1do_MSYestimation.R#L208-L217

以下，上記のコードの解説です．

```r
# オプション: Catch AAV mean((catch_y-catch_y+1)/catch_y+1)
calc.aav <- function(x) abs(diff(x))/x[-1] # aavを計算する関数を定義（こんなんでよいんでしたっけ？ちょっと適当です）
catch.aav.table <- kobeII.table %>%   # kobeII.tableから
    dplyr::filter(year%in%c(2017:2023),stat=="catch") %>%　# 2017-2013年の漁獲量を取り出し
    group_by(HCR_name,beta,sim) %>%   # HCR_name, beta, sim (シミュレーション番号)ごとにグループ化
    summarise(catch.aav=mean(calc.aav(value))) %>%  # 漁獲量の値(value)のAAVを計算し（5年分取り出しているので数字は4個づつ出てくるため），それを平均する
    group_by(HCR_name,beta) %>%   # HCR_name, beta毎にグループ化
    summarise(catch.aav.mean=mean(catch.aav)) %>%  # それぞれのシナリオごとにAAVの平均をさらに平均
    arrange(HCR_name,desc(beta))%>%   # 並び替え
    mutate(stat_name="catch.csv (recent 5 year)")　 # 新しい列に名前をつける
```

**Comment by osamusakai** [comment]
早速のご対応ありがとうございます。
動かしてみます。

ところで、以前試作されていたレーダーチャートって、もう消滅したのでしょうか？
以前、水産庁が「今後はわかりやすく見える化をしていく」と事あるごとに強調していたので、ちょっと気になっています。見える化＝レーダチャートというわけではないとは思いますが…。
βを変えるだけの比較では、不要なのかもとは思いますが。

**Comment by ichimomo** [comment]
そうですね。いろんなパフォーマンス指標に注目する場合、有効だと思うんですが、今のところのオーダーはそれほどでもないので（漁獲量・資源量・回復確率のみ）、なくても良いのかな、と。。（あとβを網羅的に変えるため、比較するシナリオ数が多くなりすぎるとか）

長期的な管理基準値については以下のように、色をつけたグラフ＋表で見せたらわかりやすい感じだったので、これでも良かな、と。
![image](https://user-images.githubusercontent.com/44047915/54890117-2f56a780-4eeb-11e9-85c9-03007bb6ccbc.png)

ただ、ここで書いていて、βを網羅的に検討したのち→特に有力候補について、レーダーチャートで表示、というのも良いのかもと思いました。特に作業部会からの指示はありませんが、考えてみます。明日からずっと水産学会でばたばたしているためすぐ対応できるかはわかりませんが、でも、科学者会議のレポートの書式も決めないとですし。。

ではでは
