### ISSUE TITLE
ブランチを切っていただけないでしょうか

### ISSUE THREAD

**Issue by kikirinrin** [ichimomo/future-rvpa#40]
ローカルでいろいろ勉強してます．

いきなり `master` にプルリク出すのははばかられるので，なにかブランチを切っていただけないでしょうか．

まずは勉強がてら，リファクタリングから始めようと思うので，`refact` とかそんな感じのブランチ名でお願いします．

**Comment by ichimomo** [comment]
すみません，じつはまだbranchの使い方についてよくわかってません．
いろいろチュートリアルとかを見ると，ローカルでの作業時での使い方↓

- ローカルでbranchを作成
- branch上で作業
- masterにmerge
- pushする

というのは見たんですが，リモート上でbranchを作成するっていうのはどうするのか？どんなふうに使うのか？など教えてくれるとありがたいです．（まだ素朴な使い方しかしたことなくて．．．）

**Comment by kikirinrin** [comment]
いきなりすみませんでした．

リモート（この場合はGitHub）でのブランチ作成は，
ブランチ切り替えボタン を押して，ウインドウに任意のブランチ名を入れるとできます（すでに存在するブランチ名を入れるとフィルタになり，存在しないブランチ名だと新規作成になります）．
<img width="595" alt="image" src="https://user-images.githubusercontent.com/14845847/55283088-f2306080-5395-11e9-9665-efe7420195ef.png">

もしブランチを切っていただけるなら，上記の方法をおすすめします．
もちろん，ローカルで作成してくださってからpushでも構わないのですが，少し手順が煩雑になります．

仰るような方法で，ローカルで `master` にマージしてから push した場合には，GitHub 上では `master` しか存在しないことになります．

**Comment by kikirinrin** [comment]
ブランチの使い方ですが，
`master` は，いつ誰が pull しても大丈夫なように，バグやUIに問題ないことが確認されたコミットだけをマージするのが主流のようです．

ブランチの切り方は自由ですが，まずは新機能開発用に `dev` を作り，足りなかったら足していけばいいのではと思います．

**Comment by kikirinrin** [comment]
今回私は，遅ればせながらコードの中身の勉強を始めたのですが，
その途中で要修正点が見つかった場合，せっかくならオリジナルコードのブラッシュアップにも貢献したいと思っています．

その場合，議論の中心にない枝葉部分の修正を `master` や `dev` に push してしまうと議論の邪魔になりますので（何より私が恥ずかしい），
「時間があったらマージしてください」的なブランチに push できると気が楽です．

`refact` ブランチが適当かもと思ったのは，そういう訳でした．
失礼しました．

**Comment by kikirinrin** [comment]
我々魚種担当が Folkした リポジトリのブランチ構成は，多分
`master` の他に魚種名（例えば `twmasaba` など）になると思います．
開発チームの変更を `master` に取り込み，それをさらに自分のデータを置いた魚種名ブランチに取り込むんだと思います．

ほんとは
```
devtools::install_github("ichimomo/future-rvpa")
library(future-rvpa)
````
で全部動くと，pull での merge だのしなくていいのでみんな楽だと思います（小声で言います）

**Comment by ichimomo** [comment]
ありがとうございます．とりあえずrefactというブランチを作ってみました．
こちらも，ちょっと使いながら慣れるという感じでよろしくお願いします．

**Comment by kikirinrin** [comment]
ありがとうございます．
主要開発メンバー以外も，恐れず pr できるようになると思います．
