### ISSUE TITLE
【質問】if 文の第2ケースはどんなデータを想定？

### ISSUE THREAD

**Issue by kikirinrin** [ichimomo/future-rvpa#41]
初歩的な質問ですみません．

https://github.com/ichimomo/future-rvpa/blob/d4351d46ced4b34d1ca7f1f7f450b3db6a4ad7a6/rvpa1.9.2.r#L43

の if 文の第2ケース
`dim(waa)[2]==1` を通るようなデータは，
どんな形なのでしょうか？
`c(0.5, 1.3, 3.5)`
のようなベクトルを与えるとエラーになってしまいます．

**Comment by kikirinrin** [comment]
それと，こういう初歩的な質問であまり Issues を汚したくないので，どと

**Comment by ichimomo** [comment]
ご質問についてですが，VPA関係の関数を作ったのは岡村さんなので推察ですが，
weight at ageやmaturity at ageが年によって変わらずに毎年同じの値を使う場合，waaとかはデータファイルから読み込まず，data.handlerの引数に c(100,200,300) とか，ベクトルを与えることでもＯＫというような仕様だと思います．

取り急ぎ

**Comment by kikirinrin** [comment]
議論の中心は HCR に移っているのに，今更 VPA 関数についての質問をしてすみませんでした．
仰るように，ここはベクトルが入ってくることを想定しているように見えますが，
```
Error in if (is.null(dim(waa)) | dim(waa)[2] == 1) waa <- as.data.frame(matrix(unlist(waa),  :
  argument is of length zero
```
となって受け付けませんでした．

HCRの議論が済んだころに，岡村さんに聞いてみます．
ありがとうございました．
優先度ラベルのようなものがありましたら，優先度を下げていただいて構いません．

**Comment by ichimomo** [comment]
いちおう，岡村さんにアサインしておきますね．
（岡村さんはあんまりgithubのページは見ていませんが．．）

**Comment by kikirinrin** [comment]
たいへん助かります！！

**Comment by OkamuraHiroshi** [comment]
どうしてそういうのを入れたのかは忘れましたが，たぶんそのときにはdata.frameでデータを扱うというイメージでいたんだと思います．

なので，とりあえず
data.frame(waa=c(0.5, 1.3, 3.5))
とかで与えればエラーは出ないのではないかと....

**Comment by kikirinrin** [comment]
岡村さん，ご指摘の通りでした．ありがとうございます．
