### ISSUE TITLE
初歩的な質問についての適当な問い合わせ先がありましたら教えてください．

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/future-rvpa#42]
初歩的な質問であまり Issues を汚したくないので，どこか適当な問い合わせ先がありましたら教えてください．

_Originally posted by @kikirinrin in https://github.com/ichimomo/future-rvpa/issues/41#issuecomment-478189778_

**Comment by ichimomo** [comment]
初歩的な質問でもむしろissueを活用して頂けるとありがたいです．
そしたら私以外にも知っている人が答えてくれると思います．
緊急の場合でissueに返事が全然ない場合は，issueを引用して，返事くださいと誰か特定の人にメールください．

どのファイルをだれがたんとうしているかはざっくりとこちらで紹介しています．
https://github.com/ichimomo/future-rvpa/blob/master/README.md#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E8%AA%AC%E6%98%8E
将来予測のほうは，来週から新しく来られる福井さん，というかたに手伝ってもらう予定です．

**Comment by kikirinrin** [comment]
はい，承知しました．ありがとうございます．

**Comment by ichimomo** [comment]
そうですね．いちおうREADMEなどでどこがだれの担当か，確認できるようにしておきます

**Comment by kikirinrin** [comment]
ありがとうございました．
