### ISSUE TITLE
Rmd  のレポートは会議で使われないのですか？

### ISSUE THREAD

**Issue by kikirinrin** [ichimomo/future-rvpa#47]
「科学者会議資料の書き方」というWordファイルがメールで送られてきたのですが，ここで開発してくださった `.Rmd` のレポートは会議で使われないのでしょうか？

[`.docx` 形式での出力](https://bookdown.org/yihui/rmarkdown/word-document.html)もできるようですし，わざわざ図を手で貼り付ける作業は，せっかくの開発努力を無駄にしてしまうのではないかと思います．

**Comment by ichimomo** [comment]
ご提案ありがとうございます。
いつかはそういう方向に向かいたいところですが、やはり正式な報告書となるとフォントがいくつだとか、ここをインデントするとかいった細かい書式を揃えないといけないようで難しい感じです。
ワードフォーマットでの出力も少し試してみましたが、なんか見栄えは悪いですよね。。。
現実的な方向性としては、

1. 新しい報告書に似せた文書のワードの雛形をrmdで出す
2. それをワードでフォーマット
3. 変更が生じた場合には手動で図表のみ張り替え

という感じかな、と思っております。1.のプロセスについて、すでに固まっている部分をrmdで出力するようなrmdを作れれば、とも思っていますが、なかなか手が足りず。。。

ということでこちらも今後の検討事項とさせてください！

**Comment by kikirinrin** [comment]
ご回答ありがとうございます。
今後の検討事項としていただき、ありがとうございます。
この4月の科学者会議をなんとか乗り切るための妥協案として、なら仕方ないかと思います。
本来なら上から「このワークフローを何とかしろ、改善のためには人手がどれだけ欲しいか言ってみろ」、という声が上がりそうなものですけど、ないですね。

**Comment by kikirinrin** [comment]
コードだけでなく報告書も、複数人の目に晒され、編集されるので、もう全部 GitHub でやればいろいろな面倒がなくなるでしょうけど、Word という足枷があるとそれも無理ですね。一旦クローズして、将来的な機能追加の要望として新しい Issueとします。失礼しました。
