### ISSUE TITLE
初期状態PCからの警告

### ISSUE THREAD

**Issue by fshin3** [ichimomo/future-rvpa#48]
git からcloneしてきた状態でfuture-doc-abc.RmdをR(ver.3.5.1) & Rstudio(ver.1.1.463)で実行すると、rmdformatsのパッケージ要求がくる。これをインストールののち実行すると「オブジェクト’opts_chunk’がありません」のエラー表示とともに停止。

**Comment by kikirinrin** [comment]
knitr のバージョンはいくつでしょうか？

**Comment by fshin3** [comment]
knitrはver.1.22でした。

**Comment by fshin3** [comment]
commitに返信すると下の階層で表示されるのみで目につきづらいとのことなので、いたずらにissueを増やすのもクローズしにくいのでこちらに再度初期状態PCからのエラー報告を記します。

tidyverseパッケージをfuture2.1.rのrequireと独立してインストールし、ライブラリで読み込んだところ、
Loading required package: tidyverse
─ Attaching packages ───────────────────────────── tidyverse 1.2.1 ─
✔ ggplot2 3.1.1 ✔ purrr 0.3.2
✔ tibble 2.1.1 ✔ dplyr 0.8.0.1
✔ tidyr 0.8.3 ✔ stringr 1.4.0
✔ readr 1.3.1 ✔ forcats 0.4.0
─ Conflicts ─────────────────────────────── tidyverse_conflicts() ─
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag() masks stats::lag()
という警告は出るものの、Line 431のエラーで停止は回避。

他方で、
Quitting from lines 444-484 (future-doc-abc.Rmd)
.External2(C_dataviewer, x, title) でエラー: unable to start data viewer
呼び出し: ... withCallingHandlers -> withVisible -> eval -> eval -> View
追加情報: 42 件の警告がありました (警告を見るには warnings() を使って下さい)
実行が停止されました

というエラーで停止。

**Comment by xiawatanabe** [comment]
中央水研の渡辺です、一番上の「 opts_chunk がありません」の警告は私もでましたが、
opts_chunk$set の前に「knitr::」と書き入れたら動きます。試してみてください。

<修整例↓>
knitr::opts_chunk$set(echo=TRUE,
#                     cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)

**Comment by ichimomo** [comment]
本件については解決したと思うので、どうなったかを書き込んで、issueをcloseしてください

**Comment by fshin3** [comment]
TMBオプション部分がうまく動きませんが、実質使えないとのことで無視すれば、これ以外は全体を通して動くようです。ただし、l.80の{r ref.F, fig.cap="図：YPR, SPR曲線"}とl.98{r ref.F3, fig.cap="図：YPR, SPR曲線 (x軸などを変更した場合)"}の作図で以下の警告が出ますが、図は描けます。
グラフィックパラメータ "cin" を設定できません
グラフィックパラメータ "cra" を設定できません
グラフィックパラメータ "csi" を設定できません
グラフィックパラメータ "cxy" を設定できません
グラフィックパラメータ "din" を設定できません
グラフィックパラメータ "page" を設定できません
