### ISSUE TITLE
utilities.rのplot_yield関数

### ISSUE THREAD

**Issue by osamusakai** [ichimomo/future-rvpa#49]
漁獲量曲線を描画する関数plot_yieldに、過去や将来の親魚量・漁獲量の時系列を重ね書きするコードがあります。
geom_pointでプロットするところは良いのですが、そのプロットを結ぶ関数として、geom_lineが使用されています。
geom_lineでは、単純にＸ軸の小さい点から大きい点に線で結んでしまう（折れ線グラフを作る）コードになるため、親魚量が単純増加・単純減少している場合なら違和感ないですが、増えたり減ったりする時系列のある資源で描画するとおかしなことになります。
geom_lineではなく、geom_pathを使えば、目論見通りの図が描けると思います。

すなわち過去については；
【現状】
`        g1 <- g1 +
            geom_point(data=tmpdata,mapping=aes(x=ssb.past,y=catch.past,
                                                alpha=year),shape=2) +
            geom_line(data=tmpdata,mapping=aes(x=ssb.past,y=catch.past),color="gray")
`

【修正】
`        g1 <- g1 +
            geom_point(data=tmpdata,mapping=aes(x=ssb.past,y=catch.past,
                                                alpha=year),shape=2) +
            geom_path(data=tmpdata,mapping=aes(x=ssb.past,y=catch.past),color="gray")
`
将来予測部分も同様です。
確認をお願いします。

**Comment by kikirinrin** [comment]
横からすみません。
酒井さんは本リポジトリをFolkwされてるようですので、お手元で修正されてから pull request で Issue を作った方が良いと思います。説明も少なくて済み、チェックする方も、差分を行単位で把握できて助かると思います。

**Comment by osamusakai** [comment]
そうですね。
今手一杯なので、少しお時間いただきますが、今後は併せてpull requestすることにします。
よろしくお願いします。

**Comment by ichimomo** [comment]
修正しました。ご指摘ありがとうございます。
pull requestして頂けるとすごくうれしいですが、もしお時間ないときは、とりあえずissueにバグ報告だけでもして頂ければ助かりますので、今後ともよろしくお願い致します。
ggplot2も、今年から使い始めたばかりなのでいろいろ間違いあるかと思います。。。
