### ISSUE TITLE
図中の数値の表記

### ISSUE THREAD

**Issue by osamusakai** [ichimomo/future-rvpa#50]
現在のコードでは、図中のケタの大きい数字は「1e+05」や「3e+06」など、指数での表記になっていますが、あまり一般受けはしないのではないかと思います。
図の描画コードの前に
`options(scipen=100)`
のように追記し、指数表示になるのを避けたほうが良いように思います。
ご検討をお願いします。

**Comment by ichimomo** [comment]
一応追記してみましたが、例コードではご利益はあまり感じられませんでした、、

そもそもＲで作るグラフの単位については、もう少しうまく表記したいと考えており、
plot_futuresでは
https://github.com/ichimomo/future-rvpa/raw/master/sample/make_report1/2make_report_files/figure-markdown_github/unnamed-chunk-4-1.png
のように、漁獲量や尾数の単位を引数に入れ、それで割った値で表示するようにしてみたんですが、
他関数でも同様のことするのかなり煩雑ですよね、、。
そして一番の問題が（気づいてませんでしたが）、もともとのVPAへのインプットの数字がどういう単位かというのは人によってばらばらで（特に尾数）、VPA上で1尾となっていても、実際には1千尾なのかもしれないし、1億尾かもしれないんですよね、、

このあたり整理し、どうやればよいか少し考えます。（が、間に合うか、、、）

**Comment by osamusakai** [comment]
おっしゃる通りで、私の担当資源では加入尾数はx1000尾です。
なので、資源量は「万トン」表記になるようにして、加入尾数はコードの表記を付け足して「1000万トン」になるようにして使っています。
今のところ、あまり時間もないので、担当者自身が自分で図の表記を手作業で弄るしかないかもしれません。Ｒに不慣れな方には大変かもしれませんが…。
