### ISSUE TITLE
autoregressiveSR2オブジェクト読み込みでエラー？

### ISSUE THREAD

**Issue by fshin3** [ichimomo/future-rvpa#52]
https://github.com/ichimomo/future-rvpa/blob/11dc120b6daaa0a586c8f6855f7e9cdbea644aa4/sample/simple/future-doc-abc.Rmd#L154-L160

ここで
MakeADFun(data, params, map = map, DLL = "autoregressiveSR2", でエラー: Error when reading the variable: 'gamma'. Please check data and parameters.
のエラーが出ます。TMBパッケージはインストールし、autoregressiveSR.cppはダウンロードして作業フォルダに置きました。

**Comment by ShotaNishijima** [comment]
以前のバージョンではMesnilのcontinuous HSを使ってて、それにはgammaという既知のパラメータが含まれていたのですが、そこから仕様が変わって、gammaという引数が取り除かれたためエラーが出たんだと思われます。いずれにせよ、TMBオプションは正確に推定できるか疑問であるため、今は実質的に使えないオプションになってます。
