### ISSUE TITLE
est.MSY() が止まる

### ISSUE THREAD

**Issue by kikirinrin** [ichimomo/future-rvpa#58]
est.MSYが
`Error in optimize(getFrec, interval = Frec$Frange, arglist = arglist) :  invalid 'xmin' value`
というエラーを吐いています．

どのあたりを調べればよいか，ご教示いただけないでしょうか．

**Comment by kikirinrin** [comment]
引数は以下のようにしています．


```r
MSY_l1_seed1 <- est.MSY(res.tgs,
                        future.Fcurrent_l1$input,
                        resid.year = 0,
                        N = 50,
                        calc.yieldcurve = TRUE,
                        PGY = c(0.95, 0.9, 0.6, 0.1),
                        onlylower.pgy = TRUE,
                        B0percent = c(0.2, 0.3, 0.4),
                        Bempirical = c(ssb_recent1, ssb_max1, hsbp1),
                        seed = 1)
```

**Comment by ichimomo** [comment]
経験的な管理基準値の計算のところでうまく初期値がみつからないんだと思います。

Estimating MSY
F multiplier= 0.523244 
Estimating PGY  90 %
F multiplier= 0.2633456 
F multiplier= 0.9540607 
Estimating PGY  60 %
F multiplier= 0.1131719 
F multiplier= 1.019431 
Estimating PGY  10 %
F multiplier= 0.01319282 
F multiplier= 1.079894 
Estimating B0  30 %
F multiplier= 0.4342835 
Estimating B0  40 %
F multiplier= 0.3071907 

とかいう出力が出ると思いますが、それが止まってるところで失敗しているだろうので、
とりあえずその管理基準値の計算は避けてみてください

trace.multi=c(seq(from=0,to=0.9,by=0.1),1,seq(from=1.1,to=2,by=0.1),3:5,7,20,100)
という引数があってデフォルトは上のようになっていますが、もう少し範囲を変えてみたらうまくいくかも。。？

**Comment by kikirinrin** [comment]
ありがとうございます．
管理基準値を一つずつ削ってみましたが，どれもだめみたいでした．

`Bempirical =` を丸ごと削除したら動きました．
とりあえず，最後まで計算したいのでこのままいきます．

ありがとうございました．
