### ISSUE TITLE
yield curveの図を描く関数（plot_yield）なのですが、なぜかアップロードされている関数で描画させると図の軸目メモリのフォントがやや灰色になることに気が付きました。描画例として挙げていただいている図では黒色なのに、なぜなのでしょう…。

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/future-rvpa#66]
yield curveの図を描く関数（plot_yield）なのですが、なぜかアップロードされている関数で描画させると図の軸目メモリのフォントがやや灰色になることに気が付きました。描画例として挙げていただいている図では黒色なのに、なぜなのでしょう…。
とりあえず、関数コードのなかのthemeに目盛を黒するコマンドを追記していただけないでしょうか？
場所はutilities.rの212行目か、そのあたりかと思います。
`theme(axis.text=element_text(color="black"))`

相変わらずプルリクエストとかでなくてすいません。

_Originally posted by @osamusakai in https://github.com/ichimomo/future-rvpa/issues/60#issuecomment-489548950_

**Comment by ichimomo** [comment]
3make_SHreport.mdでは
(g2_yield_curve <- plot_yield(MSY.base$trace,
                              refs.plot,
                              refs.label=c("目標管理基準値","限界管理基準値","禁漁水準"),
                              future=list(future.default),
                              past=res.pma,labeling=FALSE,
                              refs.color=c(1,1,1), # 印刷が出ないので縦線の色は黒にすることに
                              biomass.unit=1000,#資源量の単位
                              AR=FALSE,
                              xlim.scale=0.4,ylim.scale=1.3 # x, y軸の最大値の何倍までプロットするか。ラベルやyield curveの形を見ながら適宜調整してください
                              ))+ theme_SH()
としてtheme_SHをあとから与えて細かい描画の調整をしていたんですが、

ちなみに、theme_SHは↓
theme_SH <- function(){
    theme_bw(base_size=12) +
    theme(panel.grid = element_blank(),
          axis.text.x=element_text(size=11,color="black"),
          axis.text.y=element_text(size=11,color="black"),
          axis.line.x=element_line(size= 0.3528),
          axis.line.y=element_line(size= 0.3528),
          legend.position="none")
}
それをg2_yield_curveにセーブするときのカッコの位置が悪かったようです。調整致しました。

**Comment by osamusakai** [comment]
なるほど！
調整の取れた図になりました。
どうもありがとうございました。
