### ISSUE TITLE
betaをギリシャ文字に

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/future-rvpa#68]
https://github.com/ichimomo/future-rvpa/blob/master/sample/make_report1/3make_SHreport.md のページのkobe chartの図

g3_kobe4_F <- plot_kobe_gg(res.pma,refs.base,roll_mean=1,category=4,
                            Blow="Btarget0", Btarget="Btarget0",
                            beta=0.8, # 推奨されるβに変える
                            refs.color=c(1,1,1),
                            yscale=1.2, # y軸を最大値の何倍まで表示するか。ラベルの重なり具合を見ながら調整してください
                            ylab.type="F",Fratio=Fratio)+theme_SH())

と将来予測の図

(g4_future <- plot_futures(res.pma, #vpaの結果
                   list(future.Fcurrent,future.default), # 将来予測結果
                   future.name=c("s1","s2"),
                   CI_range=c(0.1,0.9),
                   maxyear=2045,
                   ncol=1, # 図の出力の列数。3行x1列ならncol=1
                   what.plot=c("biomass","SSB","catch"),
                   Btarget=derive_RP_value(refs.base,"Btarget0")$SSB,
                   Blimit=derive_RP_value(refs.base,"Blimit0")$SSB,
                   Bban=derive_RP_value(refs.base,"Bban0")$SSB,
                   RP_name=c("目標管理基準値","限界管理基準値","禁漁水準"),
                   biomass.unit=1000,  # バイオマスの単位(100, 1000, or 10000トン)
                   n_example=5,seed=2)+ # どのシミュレーションをピックアップするかはseedの値を変えて調整してください
    theme_SH()+
    theme(legend.position="top")+
    scale_color_hue(labels=c(VPA="過去の推定値",s1="現状の漁獲圧",s2="漁獲管理規則(beta=0.8)"))+
    scale_fill_hue(labels=c(VPA="過去の推定値",s1="現状の漁獲圧",s2="漁獲管理規則(beta=0.8)"))+
    scale_linetype_discrete(guide=FALSE)

で、beta=0.8となっているところを、β=0.8と表示されるように修正いただけないでしょうか？
できれば明日中くらいまでに、、

plot_futuresのほうは、scale_fill_hueの指定のところを変更すればよいかと思いますが、plot_kobe_ggのほうは関数そのものを変更する必要あるかと思います。
こうすれば良い、というコード例を頂ければ反映させて頂きます。

宜しくお願い致します。

**Comment by fshin3** [comment]
plot_futuresは、scale_fill_hueで
 scale_color_hue(labels=c(VPA="過去の推定値",s1="現状の漁獲圧",s2=expression(paste("漁獲管理規則(",beta,"=0.8)") ) ) )
としてみました。kobe_plotはまだ未解決です。

**Comment by fshin3** [comment]
とおもいましたが、utilities.rのエンコードがUTF-8で指定されているので、単純にbetaをβに書き換えれば表示されました。

**Comment by ichimomo** [comment]
どうもありがとうございます。盲点でした。
こちらのコミットで反映させてみました。
https://github.com/ichimomo/future-rvpa/commit/4c85cdf5b05b607130b60fac611ef51c2b5f6e1f
OSによっては不具合あるかもしれないので、不具合ありましたらご報告ください。
