### ISSUE TITLE
【質問】plot_yield() が未定義の引数を許容 ？

### ISSUE THREAD

**Issue by kikirinrin** [ichimomo/future-rvpa#70]
間抜けな質問すみません．

私の手元の古いコードで，`plot_yield()` に `AR = FALSE` を与えているのですが，
関数定義の中にはそのような引数定義はありませんよね．
定義されていない引数を与えているのになぜかエラーが出ないのですが，どうしてか教えていただけないでしょうか．

https://github.com/ichimomo/future-rvpa/blob/7f34df6225faa0b774db0de2ac604ee557e4168f/utilities.r#L163

**Comment by ichimomo** [comment]
ARという引数はないけどAR_selectという引数があるからだと思います。
Ｒの（あんまり良くない）特徴として、関数の引数として他にマッチングするものがない場合には引き数の省略が許されるというのがあります。

たとえばrnormにはsという引数はありませんが、sdという引数があり、他にsからはじまる引数をもっていないので、以下のようなコードでもエラーは出ません。
`
 rnorm(10,s=10)
`

という趣旨の答えで良いのでしょうか？
もともと問題のAR_selectオプションは、ARありの管理基準値を使う場合があまりメジャーじゃなくなっているので、少し整理しようかと思っているところです

**Comment by kikirinrin** [comment]
ドンピシャのお答え，ありがとうございます．知りませんでした．
恐ろしい仕様ですね．
勉強になりました．
