### ISSUE TITLE
kobeプロット

### ISSUE THREAD

**Issue by ShokoMorita** [ichimomo/future-rvpa#72]
図１の図中で漁獲管理規則β＝0.8　と1995年が重なってしまうのですが
漁業管理規則の文字をずらす事は可能でしょうか？

![image](https://user-images.githubusercontent.com/49628226/57283545-5c9d9480-70ea-11e9-89a5-5045e5daa79e.png)

**Comment by ichimomo** [comment]
承知しました。数時間のうちに修正致します。

**Comment by ShokoMorita** [comment]
修正希望のissueと違う場所にしてしまい、申し訳ありません。
修正可能でしたらお願いいたします。

**Comment by ichimomo** [comment]
いえいえ、単独でissueをたててもらったほうが本当は助かります。

さっきアップした修正版ではHCR.label.positionというオプションをつけたので、
ここの数字を調整してみてください。

コード例はこちらです。
https://github.com/ichimomo/future-rvpa/blob/3c55ae7a9cf5cf7e858c7a431e528aeb37d7c3dd/sample/make_report1/3make_SHreport.rmd#L90-L96

あと、ラベルと線をあんまり離してしまうと、どれが何を指しているのかわからなくなるので、必要だったらそれを示す線を上書きしてもいいのかも、、

`
(g3_kobe4_F <- g3_kobe4_F +
     geom_path(data=tibble(x=c(1.2,1.2),y=c(0.8,1.1)),
               mapping=aes(x=x,y=y),color="gray"))
`

**Comment by ShokoMorita** [comment]
ありがとうございました。

 (g3_kobe4_F <- plot_kobe_gg(res.pma,refs.base,roll_mean=1,category=4, 
                             Blow="Btarget0", Btarget="Btarget0", 
                             beta=0.8, # 推奨されるβに変える 
                             refs.color=c(1,1,1), 
                             yscale=1.2, # y軸を最大値の何倍まで表示するか。ラベルの重なり具合を見ながら
                            HCR.label.position=c(0.8,1.3),# HCRの説明を書くラベルの位置。→（1，1）から変更 
                             ylab.type="F",Fratio=Fratio)+theme_SH()) 
ggsave_SH("g3_kobe4_F.png",g3_kobe4_F)

の出力結果で大体きれいに収まりました！

![image](https://user-images.githubusercontent.com/49628226/57345144-b5217000-7184-11e9-9278-289c8fdc8f31.png)
