### ISSUE TITLE
ところで、plot_futures関数で、「Fcurrentに対する乗数」を描画するコードが追記されたと思いますが、ここで描画させているのはfuture.vpaのアウトプットのalphaでしょうか？

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/future-rvpa#76]
ところで、plot_futures関数で、「Fcurrentに対する乗数」を描画するコードが追記されたと思いますが、ここで描画させているのはfuture.vpaのアウトプットのalphaでしょうか？
このalphaはFcurrentに対する乗数ではなく、HCR実行上のFmsyからのFのmultiplierを示しているように思うのですが、いかがでしょうか？
私の勘違いかもしれませんが、確認を頂けますと幸いです。

_Originally posted by @osamusakai in https://github.com/ichimomo/future-rvpa/issues/61#issuecomment-490302182_

**Comment by ichimomo** [comment]
明日までに対応します。

**Comment by ichimomo** [comment]
いちおう修正できたと思います

**Comment by osamusakai** [comment]
意図した通りの図になりました。
ありがとうございました。
