### ISSUE TITLE
Fcurrentの図

### ISSUE THREAD

**Issue by ichimomo** [ichimomo/future-rvpa#78]
![fig2_HSL2](https://user-images.githubusercontent.com/14845847/57364913-03ebfb80-71bf-11e9-9ef2-cf6d4f5821ef.png)
Fcurrent の図の凡例に`grey` とか `tomato` が出て面白いのですが，報告書にこのまま貼って大丈夫でしょうか？

_Originally posted by @kikirinrin in https://github.com/ichimomo/future-rvpa/issues/61#issuecomment-490416817_

**Comment by ichimomo** [comment]
こちらはけっこう頑張ったんですがなかなか凡例をうまくコントロールできず、、

最新版は凡例を削除して、説明はキャプションで対応してもらえないかな、という気持ちでこんな出力になるようになっています
https://github.com/ichimomo/future-rvpa/blob/master/sample/make_report1/2make_report_files/figure-markdown_github/unnamed-chunk-4-2.png

**Comment by kikirinrin** [comment]
はい，承知しました．そのようにします．ありがとうございました．
